### PR TITLE
fix: Adjust scroll from clipping children form fields in `AlertDialog` from `showSourcesDialog`

### LINKED ISSUE #1748: bug: Slight clipping in `Alternative sources` setting
### Bug description

If the user is typing or editing the value and has their keyboard open in the `Patches organization` box, the title clips into the padding. 
Screenshot_20240306_153035_ReVanced Manager

### Version of ReVanced Manager and version & name of app you are patching

v1.19.1

### Installation method

Regular

### ReVanced Manager logs

```shell
Nil
```

### Patch logs

_No response_

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager

### PR DESCRIPTION
**Pull request by Domenic-MZS**
# 🔧🎨 UI Fix: Adjust Scroll from clipping it's children form fields in the `AlertDialog` from `showSourcesDialog` (#1748)
This PR closes #1748

### Overview
The `AlertDialog`'s scrolling behavior for `showSourcesDialog` was causing children to clip, affecting user experience and readability, especially on devices with small screens or large fonts.

- **Issue:** Children (form fields) were clipping within the `AlertDialog`.
- **Context:** The structure for managing scrolling behavior was not efficient, leading to readability issues.
- **Related Solutions:** No similar solution available.
- **Impact:** Enhances readability and usability on various devices, ensuring a smoother user experience. (For smaller devices & devices with large fonts).

### 📓 Description
This PR addresses the issue of children clipping within the `AlertDialog` by adjusting the structure to handle scrolling more efficiently. It removes unnecessary scroll components and enables the builtin scroll handle from the Flutter `AlertDialog`, ensuring content within the dialog is properly displayed without clipping.

### ✍🏼 Changes Made
- Removed child `SingleChildScrollView`.
- Added parent dialog's scrollable property to true.

### 🦯 Testing
- [x] ~Update Tests (ToDo - Not Found nor needed for now...)~
- [x] Compile/Build code 
  - 🐞 Tested with `Stable Flutter v3.19.3` and `dart 3.3.1`.
  - **System:** Linux archlinux 6.7.9-arch1-1 GNU/Linux

### 📋  Notes & References
- [Alert Dialog - scrolling](https://api.flutter.dev/flutter/material/AlertDialog-class.html#:~:text=Determines%20whether%20the%20title%20and%20content%20widgets%20are%20wrapped%20in%20a%20scrollable)

### 🔬 Reviewers
N/A (any mod is ok)

---

👾 Feedback, changes, or suggestions are welcome! ✌🏼 🏖️ now a 🍕 emoji too...

### CODE REVIEW

**Review by Domenic-MZS — COMMENTED** [review]
At first glance it LGTM (Looks Good To Me), nothing screwed up so far...

File: lib/ui/views/settings/settingsFragment/settings_manage_sources.dart [hunk 1]
```diff
@@ -27,6 +27,7 @@ class SManageSources extends BaseViewModel {
     return showDialog(
       context: context,
       builder: (context) => AlertDialog(
+        scrollable: true,
```
Comment (Domenic-MZS) [inline lib/ui/views/settings/settingsFragment/settings_manage_sources.dart:30]: I noticed that the previous AlertDialog title was fixed in-place and the modified one is scrollable along the content with this line, as the [`title` and `content` are wrapped with the `scrollable`](https://api.flutter.dev/flutter/material/AlertDialog-class.html#:~:text=Determines%20whether%20the%20title%20and%20content%20widgets%20are%20wrapped%20in%20a%20scrollable). 

It's not that big of an issue, it looks natural (even only noticed after attaching the docs & refs) but it's the cleanest way to fully address this issue on all devices. 

<details>
<summary> 🔨 Break the glass in case of concern: </summary>

> If this is unwanted, the 'hacky' alternatives would be to add extra padding or size with a `SizedBox` or `Padding` having a magic number that could not work on some specific `MediaQuery's`, virtual keyboards, or screen sizes.
</details>

**Comment by validcube** [comment]
> ## ⚒️ Build status
> ✅ Succeeded build on [22272c3](https://github.com/ReVanced/revanced-manager/commit/22272c3c320ef10b2981b31fe80776f27aad32f0).
> 
> Details: [8404775438](https://github.com/ReVanced/revanced-manager/actions/runs/8404775438)!
> 
> ### ⚙️ Workflow run configuration
> * Flutter cache: true
> * App flavor: release

### Note to team 
> [!CAUTION]
> DO NOT use the PR builder tool, this is affected by
> * #1540 
> Which causes the CI to include the changes from the PR.

File: lib/ui/views/settings/settingsFragment/settings_manage_sources.dart (hunk 1 above)
Comment (Domenic-MZS) [reply lib/ui/views/settings/settingsFragment/settings_manage_sources.dart:30]: This will be a plus because, after #1791, the title can now expand lines (jump with newlines) when it's too large to fit instead of clipping. This would make the `[AlertDialog]` content smaller and smaller (improbable but still possible), which at some point would be very hard to scroll and interact.

However, if the title and content are scrollable, this wouldn't be the case, as the user could easily scroll and focus on the content after a multi-line title.

**Comment by Axelen123** [comment]
@validcube can you review this?

**Review by validcube — APPROVED** [review]
🥞 Approved, thanks! 

## Test result (🥞 Skipped)
* Only analysis check is done, this PR is small and contains self-testing video with the fixed behaviour applied.

I shouldn't seen that first... 💀 Sorry.
