### PR TITLE
fix: Fix cancelling installation by not prematurely deleting patched APK 

### LINKED ISSUE #2224: bug: Manager sometimes immediately cancels installation and Export APK button stops working
### Bug description

Sometimes when trying to install a patched app, the Manager will immediately cancel the installation. The Export APK button will also not work. The issue only occurs when the `Save patched app` toggle in the Manager settings is enabled.

It is difficult to reproduce this bug. Below is the simplest and most consistent method I found.

**Steps to reproduce**

1. Prepare the replication environment by uninstalling YouTube ReVanced and clearing the ReVanced Manager data
2. Open the Manager settings and enable the `Allow changing patch selection` option
3. Select the suggested YouTube APK from storage
4. Patch and install YouTube with only the `GmsCore support` patch applied (the bug should not occur at this point)
5. Without closing the Manager, return to the Patcher screen and repeat step 3 and 4

The bug should occur when repeating step 4 for the second time. (You may need to try again)

Demonstration:

https://github.com/user-attachments/assets/5a5ca50d-dd6f-42f1-9236-34bacc239999

### Version of ReVanced Manager and version & name of app you are patching

1.22.0
YouTube 

### Installation method

Regular

### ReVanced Manager logs

[revanced-manager_logcat_20240923114749497367.log.txt](https://github.com/user-attachments/files/17100715/revanced-manager_logcat_20240923114749497367.log.txt)

### Patch logs

```shell
- Device Info
ReVanced Manager: 1.22.0
Model: SM-S906U1
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.youtube v19.16.39 (Suggested: 19.16.39)
Patches version: v4.15.0
Patches added: Default
Patches removed: Hide ads, Video ads, Copy video URL, Remove viewer discretion dialog, Downloads, Disable precise seeking gesture, Seekbar tapping, Swipe controls, Disable auto captions, Hide video action buttons, Hide autoplay button, Hide captions button, Hide cast button, Navigation buttons, Hide player buttons, Hide album cards, Comments, Hide crowdfunding box, Hide endscreen cards, Hide filter bar, Hide floating microphone button, Disable fullscreen ambient mode, Hide layout components, Hide info cards, Player flyout menu, Disable rolling number animations, Hide seekbar, Hide Shorts components, Disable suggested video end screen, Hide timestamp, Miniplayer, Disable player popup panels, Custom player overlay opacity, Return YouTube Dislike, Wide searchbar, Restore old seekbar thumbnails, SponsorBlock, Spoof app version, Change start page, Disable resuming Shorts on startup, Enable tablet layout, Theme, Alternative thumbnails, Bypass image region restrictions, Announcements, Always repeat, Remove background playback restrictions, Enable debugging, Spoof device dimensions, Check watch history domain name resolution, Spoof video streams, Bypass URL redirects, Remove tracking query parameter, Disable zoom haptics, Remember video quality, Playback speed, Restore old video quality menu, Open links externally
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 2 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
Aligning APK
Signing APK
Patched APK
Installing patched app
Installation canceled
```

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] The bug is only related to ReVanced Manager.

### PR DESCRIPTION
**Pull request by kitadai31**
- Fixes #2224

The issue had been caused by a race condition in asynchronous processing.
In `setLastPatchedApp()` method, `await` keyword was needed before `deleteLastPatchedApp();`

### A code to reproduce:

```dart
Future<void> deleteLastPatchedApp() async {
  final PatchedApplication? app = getLastPatchedApp();
  if (app != null) {
    print('kitadai31: (2) Starting a 2 seconds wait');
    await Future.delayed(const Duration(seconds: 2)); // <- ADDED
    print('kitadai31: (5) 2 seconds elapsed. Delete files/lastPatchedApp.apk');
    final File file = File(app.patchedFilePath);
    await file.delete();
    await _prefs.remove('lastPatchedApp');
  }
}

Future<void> setLastPatchedApp(PatchedApplication app, File outFile) async {
  print('kitadai31: (1) calling deleteLastPatchedApp()');
  deleteLastPatchedApp();
  final Directory appCache = await getApplicationSupportDirectory();
  print('kitadai31: (3) Starting copying the patched APK to files/lastPatchedApp.apk');
  app.patchedFilePath =
      outFile.copySync('${appCache.path}/lastPatchedApp.apk').path;
  print('kitadai31: (4) Copy succeeded');
  app.fileSize = outFile.lengthSync();
  await _prefs.setString('lastPatchedApp', json.encode(app.toJson()));
}
```

The code is executed in the order (1) → (2) → (3) → (4) → (5).
As a result, `lastPatchedApp.apk` is sometimes randomly deleted after copying is succeeded.

### Conclusion

The `deleteLastPatchedApp()` calling in `setLastPatchedApp()` is unnecessary from the beginning, so this PR removed this.
Because `lastPatchedApp.apk` and a pref will be overwritten without calling `deleteLastPatchedApp()`.

The calling in `reAssessPatchedApps()` is also redundant because the file does not exist, so removed.

### CODE REVIEW

**Comment by kitadai31** [comment]
#2332 (fix: Directly save APK to the cache when saving last patched app) can be reflected after this PR just to improve efficiency
but randomization should be reverted

**Review by oSumAtrIX — APPROVED** [review]

File: lib/services/manager_api.dart [hunk 1]
```diff
@@ -703,7 +702,6 @@ class ManagerAPI {
     if (lastPatchedApp != null) {
       final File file = File(lastPatchedApp.patchedFilePath);
       if (!file.existsSync()) {
-        deleteLastPatchedApp();
```
Comment (oSumAtrIX) [inline lib/services/manager_api.dart:706]: There is a comment above that needs to be adjusted.

File: lib/services/manager_api.dart [hunk 2]
```diff
@@ -372,7 +372,6 @@ class ManagerAPI {
     PatchedApplication app,
     File outFile,
   ) async {
-    deleteLastPatchedApp();
```
Comment (oSumAtrIX) [inline lib/services/manager_api.dart:375]: Is deleteLastPatchedApp used anywhere?

File: lib/services/manager_api.dart [hunk 3]
```diff
@@ -698,12 +697,11 @@ class ManagerAPI {
 
     await setPatchedApps(patchedApps);
 
-    // Delete the saved app if the file is not found.
+    // Delete the saved app pref if the file is not found.
```
Comment (oSumAtrIX) [inline lib/services/manager_api.dart:700]: When would this ever happen?

Comment (kitadai31) [reply lib/services/manager_api.dart:700]: That's true
I'll remove it

**Comment by E0697** [comment]
It doesn't seem to be fixed unfortunately. I was just able to reproduce it on v1.25.0-dev.1.

**Comment by kitadai31** [comment]
> It doesn't seem to be fixed unfortunately. I was just able to reproduce it on v1.25.0-dev.1.

Yes. This fix was accidentally rolled back while resolving conflict in another pull request.

This accident is already fixed, but the new dev release is not released due to a build failure.

**Comment by E0697** [comment]
Oh I see. Apologies and thanks a lot for the fix!

**Comment by KobeW50** [comment]
Thank you @kitadai31 

Can https://github.com/ReVanced/revanced-manager/issues/2224 be closed now? I don't have the ability to close it

Edit: Ty oSum
