### PR TITLE
fix(Updater): Handle session death

### LINKED ISSUE #3091: bug: Unable to update ReVanced Manager
### Bug description

Image

Device: Pixel 9 pro xl 
System update: March 5th 2026

### Patch logs

```shell

```

### Debug logs

Attempted to start an adb session, but when going back to the manager the update installed? So I'm unable to get adb logs for now. 

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.
- [x] The bug is only related to ReVanced Manager.

### PR DESCRIPTION
**Pull request by Ushie**
Fixes #3091

### CODE REVIEW

File: app/src/main/java/app/revanced/manager/ui/viewmodel/UpdateViewModel.kt [hunk 1]
```diff
@@ -79,14 +84,46 @@ class UpdateViewModel(
 
     private val location = fs.tempDir.resolve("updater.apk")
 
+    private var installerSessionId: ParcelUuid? = savedStateHandle["installerSessionId"]
+        set(value) {
+            field = value
+            savedStateHandle["installerSessionId"] = value
+        }
```
Comment (Axelen123) [inline app/src/main/java/app/revanced/manager/ui/viewmodel/UpdateViewModel.kt]: No need for this. use `by savedStateHandle.saveableVar` like in `PatcherViewModel`.

File: app/src/main/java/app/revanced/manager/ui/viewmodel/UpdateViewModel.kt [hunk 2]
```diff
@@ -79,14 +84,46 @@ class UpdateViewModel(
 
     private val location = fs.tempDir.resolve("updater.apk")
```
Comment (Axelen123) [inline app/src/main/java/app/revanced/manager/ui/viewmodel/UpdateViewModel.kt]: `uiTempDir` is needed to implement this properly. You may also have to change the logic in `onCleared` as well. The file should be deleted in response to a confirmation that the user wants to leave the page and cancel the update instead.

**Review by Axelen123 — CHANGES_REQUESTED** [review]

File: app/src/main/java/app/revanced/manager/ui/viewmodel/UpdateViewModel.kt (hunk 2 above)
Comment (Ushie) [reply app/src/main/java/app/revanced/manager/ui/viewmodel/UpdateViewModel.kt]: > The file should be deleted in response to a confirmation that the user wants to leave the page and cancel the update instead

I'm not sure how to impl this, a cancelUpdate() that gets called by a dialog thats shown to the user before leaving?

Comment (Axelen123) [reply app/src/main/java/app/revanced/manager/ui/viewmodel/UpdateViewModel.kt]: You would just use a `BackHandler` which deletes the files. Patcher screen does something similar.

**Comment by solrudev** [comment]
Hey, Ackpine maintainer here. I saw the issue which this PR tries to fix, and I'm not sure if this really could fix that. Was it tested and confirmed to work? It more seems like an edge case which should be handled in the library, and I'm happy to assist there.

**Comment by Ushie** [comment]
Hey!

This PR fixed the issue consistently for those who have been struggling with it, the solution is also backed by the fact that the same users were able to follow through with the installation in another part of the app which wasn't missing the savedState, but failing this that was missing it

There haven't been any reports for this screen after this fix (which makes me assume that it is fixed)

There is still another open issue regarding ackpine sessions, though: https://github.com/ReVanced/revanced-manager/issues/3034 which is the ackpine session dying despite the session being saved and reloaded

**Comment by solrudev** [comment]
I'm planning to implement detailed logging in the library, so that issues like this can be debugged more easily.

**Comment by solrudev** [comment]
Hi there. Logging have been added to Ackpine [0.22.2](https://github.com/solrudev/Ackpine/releases/tag/0.22.2) and [0.22.3](https://github.com/solrudev/Ackpine/releases/tag/0.22.3). You can give it a try.

**Comment by Axelen123** [comment]
Thank you. I will make a prerelease and try to debug the issue.

**Comment by solrudev** [comment]
Hi! There is a "Session X is dead." failure happening also in [Morphe Manager](https://github.com/MorpheApp/morphe-manager/issues/449) after migration to Ackpine.

I've released a [0.22.7](https://github.com/solrudev/Ackpine/releases/tag/0.22.7) version which tries to fix the issue. After some tests by their users, it seems that the fix is working. The issue was caused by interplay of Play Protect and some library heuristics. You can try it.
